WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/FilaTablaMultiplicar.cs
namespace PrimerMvcNetCore.Models
{
    public class FilaTablaMultiplicar
    {
        public string Operacion { get; set; }
        public int Resultado { get; set; }
    }
}

WebApplication1/Models/Persona.cs
namespace PrimerMvcNetCore.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public string Email { get; set; }
        public int Edad { get; set; }

    }
}

WebApplication1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;

namespace PrimerMvcNetCore.Controllers
{
    public class InformacionController : Controller
    {
        public IActionResult VistaControllerPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult VistaControllerPost
            (Persona persona, string aficiones)
        {
            ViewData["DATA"] = "Nombre: " + persona.Nombre
                + ", Email: " + persona.Email
                + ", Edad: " + persona.Edad
                + ", Aficiones: " + aficiones;
            return View();
        }
        public IActionResult VistaControllerGet
            (string saludo, int? year)
        {
            //PARA COMPROBAR QUE LOS HEMOS RECIBIDO,
            //GUARDAMOS LOS PARAMETROS EN ViewData
            //PARA VER LA INFORMACION
            //ViewData["DATA"] = "Hola " + saludo
            //    + " en el año " + year;
            if (year != null)
            {
                ViewData["DATA"] = "Hola " + saludo
                + " en el año " + year;
            } else
            {
                ViewData["DATA"] = "Aqui no tenemos tiempo";
            }
            return View();
        }
        public IActionResult ControladorVista()
        {
            //VAMOS A ENVIAR INFORMACION SIMPLE A NUESTRA VISTA
            ViewData["NOMBRE"] = "Alumno";
            ViewData["EDAD"] = 24;
            ViewBag.DiaSemana = "Lunes" ;
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ControladorVistaModel()
        {
            Persona persona = new Persona();
            persona.Nombre = "Alumno";
            persona.Email = "alumno@email.com";
            persona.Edad = 27;
            return View(persona);
        }
    }
}

WebApplication1/Controllers/MatematicasController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;

namespace PrimerMvcNetCore.Controllers
{
    public class MatematicasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TablaMultiplicarModel()
        {
            return View();
        }
        [HttpPost]
        public IActionResult TablaMultiplicarModel(int numero)
        {
            List<FilaTablaMultiplicar> filas =
                new List<FilaTablaMultiplicar>();
            for (int i = 1; i <= 10; i++)
            {
                FilaTablaMultiplicar fila =
                new FilaTablaMultiplicar();
                fila.Operacion = numero + " * " + i + " = ";
                fila.Resultado = numero * i;
                filas.Add(fila);
            }
            return View(filas);
        }

        public IActionResult TablaMultiplicarSimple()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TablaMultiplicarSimple(int numero)
        {
            List<int> resultados = new List<int>();
            for (int i = 1; i <= 10; i++)
            {
                int operacion = numero * i;
                resultados.Add(operacion);
            }
            return View(resultados);
        }

        public IActionResult ConjeturaCollatz()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ConjeturaCollatz(int numero)
        {
            //DEBEMOS DEVOLVER UN OBJETO COMPLEJO CON 
            //UNA LISTA DE NUMEROS
            List<int> numeros = new List<int>();
            while (numero != 1)
            {
                if (numero % 2 == 0)
                {
                    numero = numero / 2;
                }
                else
                {
                    numero = numero * 3 + 1;
                }
                numeros.Add(numero);
            }
            //DEVOLVEMOS EL MODEL A LA VISTA
            return View(numeros);
        }

        public IActionResult SumarNumerosPost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult
            SumarNumerosPost(int numero1, int numero2)
        {
            int suma = numero1 + numero2;
            ViewData["MENSAJE"] = "La suma de "
                + numero1 + " + " + numero2
                + " = " + suma;
            return View();
        }

        public IActionResult SumarNumerosGet
            (int numero1, int numero2)
        {
            int suma = numero1 + numero2;
            ViewData["MENSAJE"] = "La suma de "
                + numero1 + " + " + numero2
                + " = " + suma;
            return View();
        }
    }
}

WebApplication1/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimerMvcNetCore.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult PrimeraPagina()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Views/Informacion/ControladorVista.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 style="color: blue">
    Informacion Controller --> View
</h1>
<h2 style="color: fuchsia">
    Nombre @ViewData["NOMBRE"]
</h2>
<h2 style="color: forestgreen">
    Edad @ViewData["EDAD"]
</h2>
<h2 style="color: blueviolet">
    Día semana: @ViewBag.DiaSemana
</h2>

WebApplication1/Views/Informacion/ControladorVistaModel.cshtml
@using PrimerMvcNetCore.Models
@model Persona

<h1>
	Información Controller -> View Model
</h1>

@Html.ActionLink("Texto Link", "Action", "Controller"
	, new { variable1 = "valor1", variable2 = "valor2" })

@if  (Model != null) {
	<h2 style=" color: blue ">
		@Model.Nombre, @Model.Email, @Model.Edad
	</h2>
} else {
	<h1 style="color: red">No tenemos Model</h1>
}

WebApplication1/Views/Informacion/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Menu Informacion</h1>
<ul>
    <li>
        <a asp-controller="Informacion"
        asp-action="VistaControllerPost">
            Vista Controller POST
        </a>
    </li>
    <li>
		@Html.ActionLink("View Controller Get", "VistaControllerGet", "Informacion"
            , new { saludo = "Hola caracola", year = 2025})
    </li>
    <li>
        @Html.ActionLink("View Controller Get VACIO", "VistaControllerGet", "Informacion"
                 , new { saludo = "Estoy saludando!!!" })
    </li>
    <li>
        <a asp-controller="Informacion"
            asp-action="ControladorVista">
            Controlador --> Vista
        </a>
    </li>
    <li>
        <a asp-controller="Informacion"
           asp-action="ControladorVistaModel">
            Controlador --> Vista Model
        </a>
    </li>
</ul>

WebApplication1/Views/Informacion/VistaControllerGet.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>
    Información Vista --> Controller GET
</h1>

<h2 style="color: red">
    @ViewData["DATA"]
</h2>

WebApplication1/Views/Informacion/VistaControllerPost.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 style="color: blue">
    Vista Controller POST
</h1>

<form method="post">
    <label>Nombre</label>
	<input type="text" name="nombre"
        class="form-control"/><br/>
	<label>Email</label>
	<input type="text" name="email"
		   class="form-control"/><br/>
	<label>Edad</label>
	<input type="text" name="edad"
		   class="form-control"/><br/>
	<label>Aficiones</label>
	<input type="text" name="aficiones"
		   class="form-control"/><br/>
	<button class="btn btn-primary">
		Enviar
	</button>
</form>

<h1 style="color:green">@ViewData["DATA"]</h1>

WebApplication1/Views/Matematicas/ConjeturaCollatz.cshtml
@model List<int>

<h2 style="color:blue">
    Conjetura Collatz
</h2>

<form method="post">
    <label>Número Collatz</label>
    <input type="text" name="numero"
        class="form-control"/>
    <button class="btn btn-warning">
        Mostrar conjetura
    </button>
</form>

@if (Model != null){
    <ul>
        @foreach (int num in Model){
            <li>@num</li>
        }
    </ul>
}

WebApplication1/Views/Matematicas/Index.cshtml
<h1>Menú matemáticas Controller</h1>

<ul>
    <li>
        @Html.ActionLink("Sumar 5 + 6", "SumarNumerosGet"
        , "Matematicas", 
        new { numero1 = 5, numero2 = 6})
    </li>
    <li>
        <a asp-controller="Matematicas"
            asp-action="SumarNumerosPost">
            Sumar números POST
        </a>
    </li>
    <li>
        <a asp-controller="Matematicas"
            asp-action="ConjeturaCollatz">
            Conjetura Collatz
        </a>
    </li>
    <li>
        <a asp-controller="Matematicas"
           asp-action="TablaMultiplicarSimple">
            Tabla Multiplicar Simple
        </a>
    </li>
    <li>
        <a asp-controller="Matematicas"
           asp-action="TablaMultiplicarModel">
            Tabla Multiplicar Model
        </a>
    </li>
</ul>

WebApplication1/Views/Matematicas/SumarNumerosGet.cshtml
<h1>Sumar números Get</h1>

<h2 style="color:blue">
    @ViewData["MENSAJE"]
</h2>

WebApplication1/Views/Matematicas/SumarNumerosPost.cshtml
<h1 style="color:fuchsia">
    Sumar números POST
</h1>

<form method="post">
    <label>Número 1</label>
    <input type="text" name="numero1"
        class="form-control"/><br/>
    <label>Número 2</label>
    <input type="text" name="numero2"
        class="form-control"/><br/>
    <button class="btn btn-success">
        Sumar números
    </button>
</form>
<h3 style="color:red">
    @ViewData["MENSAJE"]
</h3>

WebApplication1/Views/Matematicas/TablaMultiplicarModel.cshtml
@using PrimerMvcNetCore.Models
@model List<FilaTablaMultiplicar>

<h1>Tabla Multiplicar simple</h1>

<form method="post">
	<label>Número</label>
	<input type="text" name="numero"
		   class="form-control" />
	<button class="btn btn-danger">
		Mostrar tabla
	</button>
</form>

@if (Model != null)
{
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Operación</th>
				<th>Resultado</th>
			</tr>
		</thead>
		<tbody>
			@foreach (FilaTablaMultiplicar fila in Model)
			{
				<tr>
					<td>@fila.Operacion</td>
					<td>@fila.Resultado</td>
				</tr>
			}
		</tbody>
	</table>
}

WebApplication1/Views/Matematicas/TablaMultiplicarSimple.cshtml
@model List<int>

<h1>Tabla Multiplicar simple</h1>

<form method="post">
	<label>Número</label>
	<input type="text" name="numero"
		class="form-control" />
	<button class="btn btn-danger">
		Mostrar tabla
	</button>
</form>

@if (Model != null) {
	<ul>
		@foreach ( int num in Model) {
			<li>@num</li>
		}
	</ul>
}

WebApplication1/Views/Prueba/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int valor = 14;
    string texto = "Hoy es lunes";
    valor += 1;
    texto += " y mañana martes¡¡";
    texto = texto.ToUpper();
}
DIBUJAR VARIABLES
<h2 style="color: red">
    Texto: @texto, Núhero: @valor
</h2>
CODIGO LOGICO CON HTML
@if (valor > 0) {
    //CODIGO C#
    texto = "POSITIVO";
    <h3 style="color: green">@texto</h3>
}else {
    //CODIGO C#
    texto = "NEGATIVO";
    <h3 style="color: red">@texto</h3>
}

WebApplication1/Views/Prueba/PrimeraPagina.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 style="color: aqua">
    Mi primera Pagina MVC de Lunes!!!
</h1>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerMvcNetCore</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimerMvcNetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimerMvcNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                            asp-controller="Matematicas"
                            asp-action="Index">
                                Matemáticas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                            asp-controller="Informacion"
                            asp-action="Index">
                                Información
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <a asp-controller="Prueba" asp-action="PrimeraPagina">
            Mi primera página
        </a> | 
        <a asp-controller="Prueba" asp-action="Index">
            Código Razor
        </a>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PrimerMvcNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>